services:
  web:
    build:
      context: .
      args:
        VITE_DISCORD_CLIENT_ID: ${VITE_DISCORD_CLIENT_ID}
        VITE_DISCORD_REDIRECT_URI: ${VITE_DISCORD_REDIRECT_URI}
        VITE_DISCORD_SCOPES: ${VITE_DISCORD_SCOPES}
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    depends_on:
      - web
    restart: unless-stopped
    volumes:
      - ./deploy/.cloudflared/config.yml:/etc/cloudflared/config.yml:ro
      - ./deploy/.cloudflared/9b32e2ee-377a-403f-8b7c-a28f5edd7bb1.json:/etc/cloudflared/9b32e2ee-377a-403f-8b7c-a28f5edd7bb1.json:ro
